### PR TITLE
Avoid using HTML tags in translation strings

### PR DESCRIPTION
**Pull request by ramiy**
https://github.com/easy-updates-manager/easy-updates-manager/pull/105

### CODE REVIEW

**Comment by ronalfy** [comment]
Heya, I had a readme issue with your last pull request, but I did the merge.

I'll have to ask @mpsparrow 's permission to add you as a contrib.

**Comment by ronalfy** [comment]
I talked to @mpsparrow and we agreed it's a bit too soon to have you listed in our readme. Please don't be offended. We want you to keep contributing, and when the time comes, we'd be happy to give you full access to the repo and add you as a contrib.

**Comment by ramiy** [comment]
It's OK, just merge my commits. Not only the translation strings, but also the readme file markdown.

**Comment by ronalfy** [comment]
Sorry, I had a merge conflict and I'm noobish at fixing those. We're done
working on readme. If you do another PR, I'll be glad to accept them.
Thanks for the help.

**Comment by ronalfy** [comment]
I merged your translation strings earlier btw.

**Pull request merged**
